---
title: "Data Prep"
format: html
editor: visual
---

Cleaned datasets pulled from .xlsx files, pulled by their independent sheets, and when possible merged by their original file, where each sheet represented a `level`

```{r}
library(tidyverse)
library(readxl)
library(janitor)
```

# Dataset on Net Attendance Rate

```{r}
primary_net_attendance_rate <- read_xlsx("../Data/Adjusted_net_attendance_rate_2022_formatted.xlsx", sheet= "Primary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total Completion" = `...6` 
) |> 
  clean_names() |>
  mutate(level = "Primary") |> 
  slice(1:203)

LowerSecondary_net_attendance_rate <- read_xlsx("../Data/Adjusted_net_attendance_rate_2022_formatted.xlsx", sheet= "Lower secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total Completion" = `...6` 
)|> 
  clean_names() |> 
  mutate(level = "Lower Secondary")|> 
  slice(1:203)

UpperSecondary_net_attendance_rate <- read_xlsx("../Data/Adjusted_net_attendance_rate_2022_formatted.xlsx", sheet= "Upper secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total Completion" = `...6` 
) |> 
  clean_names()|> 
  mutate(level = "Upper Secondary") |> 
  slice(1:203)

rbind(primary_net_attendance_rate,LowerSecondary_net_attendance_rate, UpperSecondary_net_attendance_rate) |> arrange(desc(country)) |> relocate(level, .after = unicef_sub_region_1 ) -> all_attendance
```

# Dataset on Completion Rate

```{r}
primary_completion_rate <- read_xlsx("../Data/Completion_rate_2022_formatted.xlsx", sheet= "Primary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total_Completion" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Primary") |> 
  slice(1:203)

LowerSecondary_completion_rate <- read_xlsx("../Data/Completion_rate_2022_formatted.xlsx", sheet= "Lower secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total_Completion" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Lower Secondary") |> 
  slice(1:203)

UpperSecondary_completion_rate <- read_xlsx("../Data/Completion_rate_2022_formatted.xlsx", sheet= "Upper secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...5`,
         "Total_Completion" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Upper Secondary") |> 
  slice(1:203)

rbind(primary_completion_rate,LowerSecondary_completion_rate, UpperSecondary_completion_rate) |>
  arrange(desc(country)) |>
  relocate(level, .after = unicef_sub_region_1 ) -> all_completion
```

# Dataset on Foundational Learning

```{r}
combined_foundational_edu <- read_xlsx("../Data/Foundational-learning-2022-formatted.xlsx", sheet= "Combined", skip = 1) |>
  rename(
          "Countries_Areas" = `...1`,
         "Region" = `...2`,
         "SubRegion" = `...3`,
         "Development" = `...4`,
         "Age_Group" = `...5`,
         "Subject" = `...6`,
         "Total" = `...7`
) |> filter(!is.na(Region))
```

# Dataset ICT Skills

```{r}
total_ICT_Skills <- read_xlsx("../Data/ICT-Skills_2022.xlsx", sheet= "Totals", skip = 1) |>
  rename(
         "Countries" = `...1`,
         "ISO3" = `...2`,
         "UNICEF_Region" = `...3`,
         "Sex" = `...4`,
)
Area_ICT_Skills <- read_xlsx("../Data/ICT-Skills_2022.xlsx", sheet= "Area", skip = 1) |>
  rename(
         "Countries" = `...1`,
         "ISO3" = `...2`,
         "UNICEF_Region" = `...3`,
         "Sex" = `...4`,
         "Area" = `...5`
)
Wealth_ICT_Skills <- read_xlsx("../Data/ICT-Skills_2022.xlsx", sheet= "Wealth", skip = 1) |>
  rename(
         "Countries" = `...1`,
         "ISO3" = `...2`,
         "UNICEF_Region" = `...3`,
         "Sex" = `...4`,
         "Wealth_Quint" = `...5`
)
```

# Dataset Literacy Skills

```{r}
youth_literacy <- read_xlsx("../Data/Literacy-rate_2021-1.xlsx", sheet= "Youth literacy rate, aged 15-24", skip = 1) |>
  rename(
         "ISO3" = `...1`,
         "Country" = `...2`,
         "Region" = `...3` ,
         "Development" = `...5`,
         "Total" = `...6`
) |> 
  clean_names() |> 
  mutate(level = "Youth_Aged15_24") |> 
  filter(!is.na(iso3))

adult_literacy <- read_xlsx("../Data/Literacy-rate_2021-1.xlsx", sheet= "adult literacy rate, aged 15+", skip = 1) |>
  rename(
         "ISO3" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "Development" = `...5`,
         "Total" = `...6`
) |> 
  clean_names() |> 
  mutate(level = "Adult_Aged15Up") |> 
  filter(!is.na(iso3))

rbind(adult_literacy,youth_literacy) |> 
  arrange(desc(country)) |>
  relocate(level, .after = unicef_sub_region_1 ) -> all_literacy
```

# Dataset on Out of Schools

```{r}
primary_OutSchool_rate <- read_xlsx("../Data/Out_of_school_rate_2022_formatted.xlsx", sheet= "Primary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "Development" = `...5`,
         "Total_NotInSchool" = `...6` 
)|>
  clean_names() |>  
  mutate(level = "Primary") |> 
  filter(!is.na(iso))

LowerSecondary_OutSchool_rate <- read_xlsx("../Data/Out_of_school_rate_2022_formatted.xlsx", sheet= "Lower secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "Development" = `...5`,
         "Total_NotInSchool" = `...6` 
)|> 
  clean_names() |> 
  mutate(level = "Lower Secondary") |> 
  filter(!is.na(iso))

UpperSecondary_OutSchool_rate <- read_xlsx("../Data/Out_of_school_rate_2022_formatted.xlsx", sheet= "Upper secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "Development" = `...5`,
         "Total_NotInSchool" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Upper Secondary") |> 
  filter(!is.na(iso))

rbind(primary_OutSchool_rate,LowerSecondary_OutSchool_rate,UpperSecondary_OutSchool_rate) |> 
  arrange(desc(country)) |>
  relocate(level, .after = unicef_sub_region_1) -> all_OutOfSchool
```

# Dataset on Digital Connectivity

```{r}
total_schoolage_digital_connect <-read_xlsx("../Data/School-Age-Digital-Connectivity.xlsx", sheet= "Total school age", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "IncomeGroup" = `...5`,
         "Total_DC" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Total School Age")

pre_primary_digital_connect <-read_xlsx("../Data/School-Age-Digital-Connectivity.xlsx", sheet= "Pre-primary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "IncomeGroup" = `...5`,
         "Total_DC" = `...6` 
) |> 
  clean_names() |> 
  mutate(level = "Pre-Primary")

primary_digital_connect <-read_xlsx("../Data/School-Age-Digital-Connectivity.xlsx", sheet= "Primary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "IncomeGroup" = `...5`,
         "Total_DC" = `...6` 
) |>  
  clean_names() |> 
  mutate(level = "Primary")

lower_secondary_digital_connect <-read_xlsx("../Data/School-Age-Digital-Connectivity.xlsx", sheet= "Lower Secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "IncomeGroup" = `...5`,
         "Total_DC" = `...6` 
) |>  
  clean_names() |> 
  mutate(level = "Lower Secondary")

upper_secondary_digital_connect <-read_xlsx("../Data/School-Age-Digital-Connectivity.xlsx", sheet= "Upper Secondary", skip = 1) |>
  rename( "ISO" = `...1`,
         "Country" = `...2`,
         "Region" = `...3`,
         "IncomeGroup" = `...5`,
         "Total_DC" = `...6` 
) |>  
  clean_names() |> 
  mutate(level = "Upper Secondary")

rbind(total_schoolage_digital_connect,pre_primary_digital_connect,primary_digital_connect, lower_secondary_digital_connect, upper_secondary_digital_connect) |> 
  arrange(desc(country)) |>
  relocate(level, .after = unicef_sub_region_1 ) -> all_DigitalConnectivity
```
